mysql:
  ports:
  - ${public_port}:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: ${db_password}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: 192.168.18.250:5002/admin/mysql:0.1
  stdin_open: true
