name: Apache Zookeeper
description: |
  (Experimental) Apache Zookeeper cluster
version: 1.0
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v1.0
license: 
