gitlab:
  ports:
  - ${public_port}:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ${host_labe}
  volumes:
  - /srv/gitlab/logs:/var/log/gitlab
  - /srv/gitlab/reconfigure:/var/log/gitlab/reconfigure
  - /etc/localtime:/etc/localtime
  - ${volumes_work1}:/etc/gitlab
  - ${volumes_work4}:/var/opt/gitlab
#  - ${volumes_work3}
#  - ${volumes_work2}
#  - ${volumes_work5}
  
#  hostname: ${host_labe}
  tty: true
  log_opt: {}
  image: ah.youruncloud.com/catalog/gitlab-ce
  stdin_open: true
