gitlab:
  ports:
  - ${public_port}:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ${host_labe}
  volumes:
  - /srv/gitlab/config:/etc/gitlab
  - /srv/gitlab/logs:/var/log/gitlab
  - /srv/gitlab/reconfigure:/var/log/gitlab/reconfigure
  - /srv/gitlab/data:/var/opt/gitlab
  - /etc/localtime:/etc/localtime
  hostname: ${gitlab_hostname}
  tty: true
  log_opt: {}
  image: ah.youruncloud.com/catalog/gitlab-ce
  stdin_open: true
