.catalog:
  name: gitlab
  version: 1.0.0
  description: |
    CI base of gitlab
  questions:
    - variable: host_labe
      label: "Host label to Deploy This Catalog"
      required: true
      default: "hostname=host1"
      type: "string"
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: volumes_work1
      required: true
      default: "/srv/gitlab/config:/etc/gitlab"
      type: "string"
    - variable: volumes_work2
      required: true
      default: "/srv/gitlab/logs:/var/log/gitlab"
      type: "string"
#   - variable: volumes_work3
#      required: true
#      default: "/srv/gitlab/reconfigure:/var/log/gitlab/reconfigure"
#      type: "string"
#   - variable: volumes_work4
#     required: true
#     default: "/srv/gitlab/data:/var/opt/gitlab"
#     type: "string"
#  - variable: volumes_work5
#     required: true
#     default: "/etc/localtime:/etc/localtime"
#     type: "string"
gitlab:
  scale: 1
