.catalog:
  name: gitlab
  version: 1.0.0
  description: |
    CI base of gitlab
  questions:
    - variable: "host_labe"
      label: "Host label to Deploy This Catalog"
      required: true
      default: "hostname=host1"
      type: "string"
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
gitlab:
  scale: 1
