slave:
  ports:
  - 8081:8081/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ah.youruncloud.com/catalog/kettle:v1.0.0
  links:
  - master:master
  stdin_open: true
master:
  ports:
  - 8080:8080/tcp
  - 40000:40000/tcp
  - 40001:40001/tcp
  - 40002:40002/tcp
  - 40003:40003/tcp
  - 40004:40004/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ah.youruncloud.com/catalog/kettle:v1.0.0
  stdin_open: true
