jenkins:
  ports:
  - 9001:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: index.youruncloud.com/huayun.yu/weblogic.jenkins
  volumes:
  - /var/lib/docker/:/var/lib/docker/
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/bin/docker:/usr/bin/docker
  - /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
  privileged: true
  stdin_open: true
gitlab:
  ports:
  - 9004:443/tcp
  - 9003:80/tcp
  - 9002:22/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: index.youruncloud.com/huayun.yu/weblogic.gitlab-ce
  stdin_open: true

