zookeeper:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  log_opt: {}
  image: ah.youruncloud.com/catalog/zookeeper:v1.0.0
  stdin_open: true
