redis:
  restart: always
  tty: true
  image: index.youruncloud.com/huayun.yu/weblogic.redis
  stdin_open: true
pyapp:
  restart: always
  tty: true
  image:  index.youruncloud.com/huayun.yu/weblogic.python-redis-demo:b${Build_Number}
  links:
  - 'redis:'
  stdin_open: true
pyapplb:
  ports:
  - ${Port_Number}:5000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - pyapp:pyapp
  stdin_open: true
